name: build

on:
  workflow_dispatch:
  push:

jobs: 
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v3
      - run: echo GOPATH=$(go env GOPATH) >> $GITHUB_ENV
      
      - run : go install github.com/tsliwowicz/go-wrk@latest

      - run: ls  ${{ env.GOPATH}}/bin

      - name: Create Draft Release with Tag
        uses: ncipollo/release-action@v1
        with:
          artifacts: "${{ env.GOPATH}}/bin/go-wrk"
          name: "latest"
          tag: "latest"
          generateReleaseNotes: true
          allowUpdates: true
          replacesArtifacts: true
          token: ${{ secrets.RELEASE_UPDATE }}